version: '3'

services:
  spam-detection-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=production
    command: gunicorn --bind 0.0.0.0:5001 --workers 3 app:app
