name: Publish Python Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine setuptools wheel

    - name: Build package
      run: python -m build

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      continue-on-error: true
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

    - name: Publish to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        pip install twine
        
        # Upload to PyPI
        python -m twine upload \
          --repository-url https://upload.pypi.org/legacy/ \
          --username __token__ \
          --password ${{ env.PYPI_TOKEN }} \
          dist/*
        
        # Attempt GitHub Packages upload
        python -m twine upload \
          --repository-url https://maven.pkg.github.com/${{ github.repository }} \
          --username ${{ github.actor }} \
          --password ${{ secrets.GITHUB_TOKEN }} \
          dist/*

    - name: Upload to GitHub Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh release upload v1.0.2 dist/* \
          --repo ${{ github.repository }}

    - name: Verify Package
      run: |
        echo "Dist directory contents:"
        ls -l dist/
        pip install dist/spam_detection_system-*.whl
        python -c "import spam_detection_system; print(spam_detection_system.__version__)"

    - name: Debug Failure
      if: failure()
      run: |
        echo "Workflow failed. Check previous steps for detailed error messages."
        pip list
        python --version
