name: Publish Python Package

on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Debug Repository Information
      run: |
        echo "GitHub Repository: ${{ github.repository }}"
        echo "GitHub Actor: ${{ github.actor }}"
        echo "Workflow Trigger: ${{ github.event_name }}"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine setuptools wheel

    - name: Build package
      run: |
        python -m build
        echo "Build contents:"
        ls -l dist/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      continue-on-error: true
      with:
        user: __token__
        password: ${{ secrets.PYPI_API_TOKEN }}

    - name: Publish to GitHub Packages
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Attempting to upload to GitHub Packages"
        pip install twine
        python -m twine upload \
          --repository-url https://maven.pkg.github.com/${{ github.repository }} \
          --username ${{ github.actor }} \
          --password ${{ secrets.GITHUB_TOKEN }} \
          dist/* || echo "GitHub Packages upload failed"

    - name: Detailed Package Verification
      run: |
        echo "Dist directory contents:"
        ls -l dist/
        echo "Attempting to install package from dist:"
        pip install dist/spam_detection_system-*.whl || echo "Local package install failed"
        
        echo "Attempting PyPI install:"
        pip install spam-detection-system || echo "PyPI install failed"
        
        python -c "import spam_detection_system; print(spam_detection_system.__version__)" || echo "Import failed"

    - name: Debug Failure
      if: failure()
      run: |
        echo "Workflow failed. Check previous steps for detailed error messages."
        pip list
        python --version
